#!/bin/bash

# Assume that this is being run in the smads_simulation directory
CurDir=`pwd`

echo "export ROS_PACKAGE_PATH=$CurDir:$CurDir/enml:$CurDir/amrl_msgs:$CurDir/ut_multirobot_sim:$CurDir/vector_display:\$ROS_PACKAGE_PATH" >> ~/.bashrc

source ~/.bashrc
